/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_devcore_jni_WinMultitouch */

#ifndef _Included_org_devcore_jni_WinMultitouch
#define _Included_org_devcore_jni_WinMultitouch
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     org_devcore_jni_WinMultitouch
	 * Method:    initTouch
	 * Signature: (J)I
	 */
	JNIEXPORT jint JNICALL Java_org_devcore_win_WinMultitouch_initTouch
	(JNIEnv *, jobject, jlong);

	/*
	 * Class:     org_devcore_jni_WinMultitouch
	 * Method:    dispose
	 * Signature: ()V
	 */
	JNIEXPORT void JNICALL Java_org_devcore_win_WinMultitouch_dispose
	(JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
